project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog"
  #site-url: https://19sarkars.github.io/MLBlog/
  description: "This is Shivangi Sarkar's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/19sarkars
format:
  html:
    theme: morph
    css: styles.css

editor: visual

execute:
  freeze: auto

