---
title: 'Probability Theory and Random Variables'
author: 'Shivangi Sarkar'
date: '2023-11-10'
categories: ['Probability']
description: 'An introduction to probability theory and random variables.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# What is probability theory?

Probability theory is something you may remember if you have taken combinatorics. As we know, probability refers to the chance of an event occurring. As for probability theory, it relies on probability distributions and random variables to determine the outcome of a situation.

# What is an event?

An event is simply an outcome from an experiment. For example, if I went outside (this is the experiment), it could be raining, or it may be freezing cold, or hot and humid. All of these possibilities would be considered events that could result from going outside.

# What are random variables?

Random variables are essentially variables that can take on multiple values (these are the possible outcomes from an experiment). Random variables play an important role in Probability Theory. 

An easy example of this is the value of a six-sided die. We can define a random variable X, which represents the outcome of the roll. In this case, X could take on the following values: 1, 2, 3, 4, 5, 6.

# How is probability theory applied in machine learning?

Probability theory plays an important role in this field. Just as how we can use probability theory to make predictions on what will occur, it can be used by machine learning models to make predictions based on the data it is trained on. For example, in the field of ML, Bayesian inferences are directly tied to probability theory. They rely on prior knowledge and new data to make inferences.

## Code Example
```{python}
# Let's view an example of what a probability distribution plot looks like
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Generate random data from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Plot the histogram
plt.hist(data, bins=30, density=True, alpha=0.5, color='b')

# Plot the probability density function (PDF) of the normal distribution
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, 0, 1)
plt.plot(x, p, 'k', linewidth=2)

plt.title('Normal Distribution and PDF')
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.show()
```