---
title: 'Clustering'
author: 'Shivangi Sarkar'
date: '2023-11-15'
categories: ['Clustering', 'Unsupervised learning']
description: 'An introduction to clustering.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# What is clustering?

Clustering is an unsupervised learning method in machine learning. In unsupervised learning, the input data is unlabeled and it is therefore the machine learning model’s job to find correlation between the data points. Specifically, clustering divides a set of data points into groups, where in each group, the data points are similar in some aspect. Each of these groups is called a “cluster”.

# Why do we need clustering?

You may be wondering why we need this method in the first place. Clustering is extremely useful in cases where the data present is not labeled.

# What are the types of clustering?

The types of clustering methods are listed below:

1. Centroid-based clustering: Organizes data into non-hierarchical clusters
2. Density-based clustering: Connects areas of high densities into clusters
3. Distribution-based clustering: Clusters data composed of distributions
4. Hierarchical clustering: This method creates a tree of clusters

# Real-world Applications

### Listed below are the a few of the real world applications of clustering:

* Cybersecurity: It can prevent cyberattacks by observing patterns of network traffic or system behavior
* Crime analysis: Clustering can help to determine hotspots where criminal activity could occur, as well to predict future crime trends
* Climate analysis: Clustering can allow us to observe and understand climate change as group patterns of weather conditions
* Social network analysis: We can use clustering to group social networks users together based on similarities. This could in turn be used for targeted advertising and making content recommendations

## Code Example
```{python}
# Let's take a look at how K-means clustering can work on randomly generated data
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

np.random.seed(42)

X= -2 * np.random.rand(100,2)
X1 = 1 + 2 * np.random.rand(50,2)
X[50:100, :] = X1
plt.scatter(X[ : , 0], X[ :, 1], s = 50, c = 'b')
plt.show()
```
```{python}
# Now let's take those random data points and apply K-Means clustering to them
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X)
centers = kmeans.cluster_centers_
labels = kmeans.labels_

plt.scatter(X[:, 0], X[:, 1], c=labels, s=30, cmap='viridis', alpha=0.8)
plt.scatter(centers[:, 0], centers[:, 1], c='red', s=200, marker='X', label='Cluster Centers')
plt.title('K-Means Clustering Results')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.show()
```